### ISSUE TITLE
How do I setup and run

### ISSUE THREAD

**Issue by spkprav** [ciurana2016/predict_stock_py#1]
I tried running this, but I am getting error.
Can you guide me in the right way to install this?
Or a `requirement.txt` file will help too.

**Comment by ciurana2016** [comment]
@spkprav I uploaded a requirements file, I tried it myself on a virtualenv, make sure to run this before installing requirements:
`python -m pip install --upgrade pip`

**Comment by ciurana2016** [comment]
@spkprav Is it working now ?

**Comment by spkprav** [comment]
@ciurana2016 Sorry for the late response, It work :+1:
